replicaCount: 1

clusterDomain: cluster.local

image:
  repository: gitea/gitea
  tag: latest
  pullPolicy: Always
  rootless: true # only possible when running 1.14 or later

imagePullSecrets: []

# Security context is only usable with rootless image due to image design
podSecurityContext:
  fsGroup: 1000

containerSecurityContext: {}
securityContext: {}

service:
  http:
    type: ClusterIP
    port: 3000
    clusterIP: None
    loadBalancerSourceRanges: []
    annotations:
  ssh:
    type: ClusterIP
    port: 22
    clusterIP: None
    loadBalancerSourceRanges: []
    annotations:

ingress:
  enabled: true
    # className: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.kube
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: 
  kubernetes.io/arch: amd64

tolerations: []

affinity: {}

statefulset:
  env: []
  terminationGracePeriodSeconds: 60
  labels: {}

persistence:
  enabled: true
  # existingClaim:
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  labels: {}
  annotations: {}
  # storageClass:
  # subPath:

# additional volumes to add to the Gitea statefulset.
extraVolumes:
extraVolumeMounts:

initPreScript: ""
#
# initPreScript: |
#   mkdir -p /data/git/.postgresql
#   cp /pg-ssl/* /data/git/.postgresql/
#   chown -R git:git /data/git/.postgresql/
#   chmod 400 /data/git/.postgresql/postgresql.key

# Configure commit/action signing prerequisites
signing:
  enabled: false
  gpgHome: /data/git/.gnupg

gitea:
  admin:
    #existingSecret: gitea-admin-secret
    username: gitea_admin
    password: admin
    email: "gitea@local.domain"

  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      #  additionalLabels:
      #    prometheus-release: prom1

  ldap: []
  oauth: []
  config: {}
  #  APP_NAME: "Gitea: Git with a cup of tea"
  #  RUN_MODE: dev
  #
  #  server:
  #    SSH_PORT: 22
  #
  #  security:
  #    PASSWORD_COMPLEXITY: spec

  additionalConfigSources: []
  #   - secret:
  #       secretName: gitea-app-ini-oauth
  #   - configMap:
  #       name: gitea-app-ini-plaintext

  podAnnotations: {}
  #livenessProbe:
  #  tcpSocket:
  #    port: http
  #  initialDelaySeconds: 200
  #  timeoutSeconds: 1
  #  periodSeconds: 10
  #  successThreshold: 1
  #  failureThreshold: 10

  # Modify the readiness probe for your needs or completely disable it by commenting out.
  #readinessProbe:
  #  tcpSocket:
  #    port: http
  #  initialDelaySeconds: 5
  #  timeoutSeconds: 1
  #  periodSeconds: 10
  #  successThreshold: 1
  #  failureThreshold: 3

memcached:
  enabled: true
  service:
    port: 11211

postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  persistence:
    size: 10Gi

mysql:
  enabled: false

mariadb:
  enabled: false

# By default, removed or moved settings that still remain in a user defined values.yaml will cause Helm to fail running the install/update.
# Set it to false to skip this basic validation check.
checkDeprecation: true
